---
- name: setup of jenkins and required softwares
  hosts: jenkins
  become: yes
  tasks: 
    - name: install required softwares
      apt: 
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: openjdk-11-jdk,b: yes}
        - {a: git,b: no}
        - {a: maven,b: no}
    - name: download the jenkins.war
      get_url:
         url: https://get.jenkins.io/war-stable/2.375.1/jenkins.war
         dest: /home/ubuntu   
- name: intstall tomcat9 and required softwares
  hosts: qa_prodserver
  tasks:
    - name: install tomcat9
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: tomcat9,b: yes}
        - {a: tomcat9-admin,b: no}
    - name: edit the tomcat-users.xml file
      copy: 
        src: tomcat-users.xml
        dest: /etc/tomcat9
      notify: restart tomcat9
  handlers: 
    - name: restart tomcat9
      service:
        name: tomcat9
        state: restarted
...          
        














