---
- name: implementing docker compose using ansible 
  hosts: all
  tasks:
    - name: create sql ccontainer 
      docker_container:
          name: mydb
          image: mysql:5
          env: 
            MYSQL_ROOT_PASSWORD: "chaitanya"
    - name: create a wordpress container
      docker_container:
          name: mywordpress
          image: wordpress
          ports:
            - 8888:80
          links: 
            - mydb:mysql           

