---
- name: implementing playscope variables
  hosts: all
  vars: 
    - a: tomcat9
    - b: present
    - c: yes
  tasks: 
     - name: install softwares
       apt: 
         name: "{{a}}"
         state: "{{b}}"
         update_cache: "{{c}}"

...         
