---
- name: name creation using host scope varbles
  hosts: 172.31.1.12
  tasks: 
    - name: create a user 
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: "{{d}}"
        comment: "{{e}}"
        shell: "{{f}}"

...        
