---
- name: install s/w's bassed on os type
  hosts: all
  tasks:
   - name: install git using apt module 
     apt:
       name: git
       state: present
       update_cache: yes
     when: ansible_distribution == "ubuntu"
   - name: install git using yum module
     yum: 
       name: git 
       state: present
       update_cache: yes 
     when: ansible_distribution == "RedHat"



...      
