---
- name: create users and create files/dirs in the users home directory
  hosts: all
  tasks: 
    - name: create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: create file 
      file:
        name: "{{d}}"
        state: "{{e}}"

